### ISSUE TITLE
plan.parameter_defaults is a list, not a string, so .split(',') fails

### ISSUE THREAD

**Issue by CFields651** [yogananth-subramanian/post-deployment-validate#1]
TASK [osp/common : Extract required variables from plan-environment] *************************************************************************************************task path: /home/stack/post-deployment-validate/roles/osp/common/tasks/main.yml:73fatal: [undercloud-0]: FAILED! => {    "msg": "The task includes an option with an undefined variable. The error was: 'list object' has no attribute 'split'\n\nThe error appears to have been in '/home/stack/post-deployment-validate/roles/osp/common/tasks/main.yml': line 73, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Extract required variables from plan-environment\n  ^ here\n"}

from plan-environment.yaml:
    NeutronPhysicalDevMappings:
    - sriov-partition-0:ensaf0
    - sriov-partition-0:ensbf0
    - sriov-partition-1:ensaf1
    - sriov-partition-1:ensbf1
    - sriov1:enscf0
    - sriov2:enscf1

Line 73 of /roles/osp/common/tasks/main.yml
- name: Extract required variables from plan-environment
  set_fact:
    bridge_mappings_tmp: "{{ bridge_mappings_tmp +(plan.parameter_defaults|to_json|from_json |json_query(_query))[0].split(',')|default([]) }}"
  when: plan.parameter_defaults|to_json|from_json |json_query(_query)
  vars:
    _query: "*.NeutronPhysicalDevMappings"

In this line .split(',') fails because this is a list and not a string.  The a simple correction is to remove the .split(',') - in my case this works:

bridge_mappings_tmp: "{{ bridge_mappings_tmp +(plan.parameter_defaults|to_json|from_json |json_query(_query))[0]|default([]) }}"

But, I'm not sure if this needs to be tested for being a string or a list as in lines 58-66.

**Comment by yogananth-subramanian** [comment]
Thank you for bringing the issue to attention and  the suggestion for the fix , will  update Line [73](https://github.com/yogananth-subramanian/post-deployment-validate/blob/master/roles/osp/common/tasks/main.yml#L73) of /roles/osp/common/tasks/main.yml  with the fix, by considering the value as list, for now.
As you have suggested, will double check if the value need to be considered as string and add support for that too.
